<?php

namespace Database\Seeders;

use App\Models\PortfolioCategory;
use App\Models\PortfolioProject;
use App\Models\User;
use Illuminate\Database\Seeder;

class PortfolioSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::query()->where('is_admin', true)->first();

        $categories = collect([
            [
                'name' => 'Branding',
                'slug' => 'branding',
                'description' => 'Projetos de identidade visual com foco em posicionamento de marca.',
                'color_hex' => '#B9822B',
                'seo_title' => 'Cases de Branding | Portfolio Uriah Criativa',
                'seo_description' => 'Cases de branding, identidade e materiais estrategicos para marcas locais e regionais.',
                'sort_order' => 10,
                'is_active' => true,
            ],
            [
                'name' => 'Materiais Promocionais',
                'slug' => 'materiais-promocionais',
                'description' => 'Campanhas impressas voltadas para conversao em ponto de venda.',
                'color_hex' => '#4F7D42',
                'seo_title' => 'Cases de Materiais Promocionais | Portfolio Uriah Criativa',
                'seo_description' => 'Vitrine de campanhas promocionais com flyers, encartes, displays e kits comerciais.',
                'sort_order' => 20,
                'is_active' => true,
            ],
            [
                'name' => 'Embalagens',
                'slug' => 'embalagens',
                'description' => 'Solucoes de embalagem com apelo visual e funcionalidade logistica.',
                'color_hex' => '#2E6FAE',
                'seo_title' => 'Cases de Embalagens | Portfolio Uriah Criativa',
                'seo_description' => 'Projetos de embalagens para varejo, food service e produtos premium.',
                'sort_order' => 30,
                'is_active' => true,
            ],
            [
                'name' => 'Comunicacao Visual',
                'slug' => 'comunicacao-visual',
                'description' => 'Materiais de sinalizacao e ambientacao para lojas e eventos.',
                'color_hex' => '#7A5C9D',
                'seo_title' => 'Cases de Comunicacao Visual | Portfolio Uriah Criativa',
                'seo_description' => 'Projetos de fachada, adesivacao, sinalizacao interna e pecas de impacto visual.',
                'sort_order' => 40,
                'is_active' => true,
            ],
            [
                'name' => 'Editorial',
                'slug' => 'editorial',
                'description' => 'Materiais editoriais com foco em legibilidade, acabamento e narrativa visual.',
                'color_hex' => '#A85B4B',
                'seo_title' => 'Cases Editoriais | Portfolio Uriah Criativa',
                'seo_description' => 'Catalogos, revistas e materiais institucionais com qualidade de impressao premium.',
                'sort_order' => 50,
                'is_active' => true,
            ],
        ])->mapWithKeys(fn (array $row) => [
            $row['slug'] => PortfolioCategory::query()->updateOrCreate(['slug' => $row['slug']], $row),
        ]);

        $projects = [
            [
                'slug' => 'rebranding-cafe-serra-verde',
                'title' => 'Rebranding da Serra Verde Cafes Especiais',
                'category_slug' => 'branding',
                'is_featured' => true,
                'client_name' => 'Serra Verde Cafes',
                'industry' => 'Alimentos e Bebidas',
                'location' => 'Campinas, SP',
                'project_year' => 2025,
                'project_url' => 'https://example.com/cases/serra-verde',
                'cover_image_url' => '/demo/banners/cartao-visita-premium.svg',
                'summary' => 'Reposicionamento completo da marca, incluindo papelaria, rotulos e material de PDV para novas franquias.',
                'challenge' => "A marca havia crescido sem padrao visual.\n\nHavia inconsistencias entre loja fisica, rotulos e materiais comerciais.",
                'solution' => "Criamos nova arquitetura de marca, paleta com alto contraste e um sistema modular de aplicacao.\n\nPadronizamos todos os impressos de contato e conversao.",
                'results' => "Em 90 dias, a marca abriu 2 novas unidades com comunicacao consistente.\n\nA adesao ao kit de materiais padrao chegou a 100% na equipe comercial.",
                'services' => ['Estrategia de Marca', 'Design de Identidade', 'Papelaria Corporativa', 'PDV'],
                'tools' => ['Adobe Illustrator', 'Adobe InDesign', 'Figma'],
                'metrics' => [
                    ['label' => 'Novas unidades', 'value' => '2 em 90 dias', 'highlight' => true],
                    ['label' => 'Materiais padronizados', 'value' => '14 pecas', 'highlight' => false],
                    ['label' => 'Adocao interna', 'value' => '100%', 'highlight' => true],
                ],
                'content' => "Projeto completo de rebranding com entrega de guia de aplicacao, mockups e arquivo final pronto para producao.",
                'published_at' => now()->subDays(35),
                'seo_title' => 'Case: Rebranding Serra Verde Cafes | Portfolio Uriah Criativa',
                'seo_description' => 'Veja como o rebranding da Serra Verde elevou consistencia visual e apoiou expansao da rede.',
                'focus_keyword' => 'rebranding para cafeteria',
            ],
            [
                'slug' => 'campanha-inverno-boutique-urbana',
                'title' => 'Campanha de Inverno da Boutique Urbana',
                'category_slug' => 'materiais-promocionais',
                'is_featured' => true,
                'client_name' => 'Boutique Urbana',
                'industry' => 'Varejo de Moda',
                'location' => 'Sao Paulo, SP',
                'project_year' => 2025,
                'project_url' => 'https://example.com/cases/boutique-urbana',
                'cover_image_url' => '/demo/banners/promocionais-campanha.svg',
                'summary' => 'Planejamento e execucao de kit promocional sazonal com foco em trafego para lojas fisicas.',
                'challenge' => "A campanha de inverno precisava gerar fluxo rapido em 3 bairros diferentes.\n\nAs acoes anteriores tinham baixa memorizacao de oferta.",
                'solution' => "Desenvolvemos flyers com segmentacao por bairro, cupom rastreavel e material de vitrine integrado.\n\nCriamos pecas com hierarquia visual orientada a conversao.",
                'results' => "A campanha superou a meta de visitas nas 3 primeiras semanas.\n\nO cupom impresso representou parcela relevante das vendas no periodo.",
                'services' => ['Direcao Criativa', 'Design Promocional', 'Impressao Offset', 'Distribuicao'],
                'tools' => ['Adobe Photoshop', 'Adobe InDesign'],
                'metrics' => [
                    ['label' => 'Aumento de visitas', 'value' => '+38%', 'highlight' => true],
                    ['label' => 'Cupons resgatados', 'value' => '1.247', 'highlight' => true],
                    ['label' => 'Lojas atendidas', 'value' => '3 unidades', 'highlight' => false],
                ],
                'content' => "A campanha foi desenhada com testes A/B de headlines e consolidada em um playbook para novas sazonalidades.",
                'published_at' => now()->subDays(32),
                'seo_title' => 'Case: Campanha de Inverno no Varejo | Portfolio Uriah Criativa',
                'seo_description' => 'Case promocional com flyers e vitrine que elevou o fluxo em lojas de moda.',
                'focus_keyword' => 'campanha promocional para varejo',
            ],
            [
                'slug' => 'linha-premium-embalagens-natural-essence',
                'title' => 'Linha Premium de Embalagens da Natural Essence',
                'category_slug' => 'embalagens',
                'is_featured' => false,
                'client_name' => 'Natural Essence',
                'industry' => 'Cosmeticos',
                'location' => 'Curitiba, PR',
                'project_year' => 2024,
                'project_url' => 'https://example.com/cases/natural-essence',
                'cover_image_url' => '/demo/banners/adesivamento-vinil.svg',
                'summary' => 'Criacao de embalagem premium para linha de skincare com melhor percepcao no ponto de venda.',
                'challenge' => "A linha premium precisava diferenciar-se sem elevar demais o custo unitario.\n\nA embalagem antiga era visualmente generica.",
                'solution' => "Redesenhamos estrutura grafica, escolhemos substrato com toque refinado e verniz seletivo.\n\nDefinimos padrao de cor e tipografia para escalabilidade de linha.",
                'results' => "A nova apresentacao aumentou percepcao de valor e facilitou venda em canais especializados.",
                'services' => ['Design de Embalagem', 'Prototipagem', 'Ajuste para Producao'],
                'tools' => ['Adobe Illustrator', 'Esko ArtiosCAD'],
                'metrics' => [
                    ['label' => 'SKUs padronizados', 'value' => '12 produtos', 'highlight' => false],
                    ['label' => 'Percepcao de valor', 'value' => '+27%', 'highlight' => true],
                    ['label' => 'Reducao de retrabalho', 'value' => '-31%', 'highlight' => true],
                ],
                'content' => "Projeto tecnico e criativo com matriz de versoes por fragrancia, mantendo unidade visual da linha.",
                'published_at' => now()->subDays(29),
                'seo_title' => 'Case: Embalagem Premium para Skincare | Portfolio Uriah Criativa',
                'seo_description' => 'Como a Natural Essence elevou percepcao de valor com design de embalagem premium.',
                'focus_keyword' => 'design de embalagem premium',
            ],
            [
                'slug' => 'sinalizacao-evento-tech-future-summit',
                'title' => 'Sinalizacao do Evento Tech Future Summit',
                'category_slug' => 'comunicacao-visual',
                'is_featured' => false,
                'client_name' => 'Tech Future Summit',
                'industry' => 'Eventos e Tecnologia',
                'location' => 'Sao Paulo, SP',
                'project_year' => 2025,
                'project_url' => 'https://example.com/cases/tech-future',
                'cover_image_url' => '/demo/banners/comunicacao-visual-pdv.svg',
                'summary' => 'Projeto de sinalizacao interna e externa para evento com mais de 8 mil visitantes.',
                'challenge' => "O evento precisava orientar alto volume de publico em multiplas trilhas de conteudo.\n\nAs edicoes anteriores tiveram gargalos de deslocamento.",
                'solution' => "Criamos sistema cromatico por trilha, totems modulares e mapas com leitura rapida.\n\nA instalacao foi planejada por etapas para reduzir tempo de montagem.",
                'results' => "A navegacao no evento ficou mais fluida e reduziu filas nos pontos de informacao.",
                'services' => ['Wayfinding', 'Sinalizacao de Evento', 'Producao de Grandes Formatos'],
                'tools' => ['Adobe Illustrator', 'SketchUp'],
                'metrics' => [
                    ['label' => 'Visitantes', 'value' => '8.200', 'highlight' => false],
                    ['label' => 'Pontos sinalizados', 'value' => '64', 'highlight' => false],
                    ['label' => 'Reducao de duvidas', 'value' => '-42%', 'highlight' => true],
                ],
                'content' => "A solucao de wayfinding foi validada com mapa de fluxo e ajustes em tempo real durante montagem.",
                'published_at' => now()->subDays(26),
                'seo_title' => 'Case: Sinalizacao para Evento de Grande Porte | Portfolio Uriah Criativa',
                'seo_description' => 'Sistema de sinalizacao para evento tech com alto fluxo e navegacao intuitiva.',
                'focus_keyword' => 'sinalizacao para eventos',
            ],
            [
                'slug' => 'catalogo-tecnico-industrial-vortex',
                'title' => 'Catalogo Tecnico Industrial Vortex',
                'category_slug' => 'editorial',
                'is_featured' => false,
                'client_name' => 'Vortex Equipamentos',
                'industry' => 'Industria',
                'location' => 'Joinville, SC',
                'project_year' => 2024,
                'project_url' => 'https://example.com/cases/vortex-catalogo',
                'cover_image_url' => '/demo/banners/papelaria-premium.svg',
                'summary' => 'Projeto editorial de catalogo tecnico com estrutura pensada para equipes de vendas B2B.',
                'challenge' => "O catalogo antigo tinha excesso de texto e baixa escaneabilidade.\n\nO time comercial perdia tempo em explicacoes repetitivas.",
                'solution' => "Reestruturamos conteudo em blocos por aplicacao, com tabelas claras e indices funcionais.\n\nAplicamos padrao grafico para atualizacoes futuras sem retrabalho.",
                'results' => "A equipe comercial reportou ganho de agilidade em apresentacoes e melhor compreensao tecnica.",
                'services' => ['Projeto Editorial', 'Diagramacao Tecnica', 'Preparacao para Impressao'],
                'tools' => ['Adobe InDesign', 'Adobe Illustrator'],
                'metrics' => [
                    ['label' => 'Produtos mapeados', 'value' => '96 itens', 'highlight' => false],
                    ['label' => 'Tempo de apresentacao', 'value' => '-28%', 'highlight' => true],
                    ['label' => 'Versoes de idioma', 'value' => '3', 'highlight' => false],
                ],
                'content' => "Foi criado template editorial reutilizavel para novas linhas, mantendo consistencia visual e tecnica.",
                'published_at' => now()->subDays(23),
                'seo_title' => 'Case: Catalogo Tecnico B2B | Portfolio Uriah Criativa',
                'seo_description' => 'Veja como um catalogo tecnico bem estruturado aumentou eficiencia comercial da Vortex.',
                'focus_keyword' => 'catalogo tecnico industrial',
            ],
            [
                'slug' => 'kit-franquia-burger-house',
                'title' => 'Kit de Franquia da Burger House',
                'category_slug' => 'branding',
                'is_featured' => false,
                'client_name' => 'Burger House',
                'industry' => 'Alimentacao',
                'location' => 'Belo Horizonte, MG',
                'project_year' => 2025,
                'project_url' => 'https://example.com/cases/burger-house',
                'cover_image_url' => '/demo/banners/cartao-visita-premium.svg',
                'summary' => 'Criacao de kit visual e operacional para abertura de novas franquias da rede.',
                'challenge' => "A expansao exigia padrao de comunicacao replicavel em cada praca.\n\nHavia variacao de fornecedores e resultado visual inconsistente.",
                'solution' => "Desenvolvemos kit com manual de aplicacao, templates e pecas prioritarias para lancamento.\n\nPadronizamos especificacoes de papel, cor e acabamento.",
                'results' => "Novas franquias passaram a inaugurar com identidade consistente e menor tempo de implantacao.",
                'services' => ['Branding', 'Manual de Marca', 'Kit de Abertura'],
                'tools' => ['Adobe Illustrator', 'Notion'],
                'metrics' => [
                    ['label' => 'Pecas padronizadas', 'value' => '22', 'highlight' => false],
                    ['label' => 'Tempo de implantacao', 'value' => '-35%', 'highlight' => true],
                    ['label' => 'Franquias atendidas', 'value' => '7', 'highlight' => false],
                ],
                'content' => "O kit foi pensado para equipes locais executarem com autonomia mantendo padrao da rede.",
                'published_at' => now()->subDays(20),
                'seo_title' => 'Case: Kit de Franquia para Rede de Alimentacao | Portfolio Uriah Criativa',
                'seo_description' => 'Padronizacao visual para franquias com ganho de velocidade e consistencia de marca.',
                'focus_keyword' => 'kit de franquia branding',
            ],
            [
                'slug' => 'lancamento-condominio-viva-park',
                'title' => 'Lancamento Imobiliario Viva Park',
                'category_slug' => 'materiais-promocionais',
                'is_featured' => false,
                'client_name' => 'Viva Park Empreendimentos',
                'industry' => 'Imobiliario',
                'location' => 'Ribeirao Preto, SP',
                'project_year' => 2025,
                'project_url' => 'https://example.com/cases/viva-park',
                'cover_image_url' => '/demo/banners/promocionais-campanha.svg',
                'summary' => 'Estrategia de impressos para stand de vendas com foco em geracao de leads qualificados.',
                'challenge' => "O stand de vendas precisava converter visitantes em contatos com rapido entendimento do projeto.\n\nMateriais antigos eram genericos e pouco persuasivos.",
                'solution' => "Criamos folder por perfil de comprador, mapa de implantacao e kit de apresentacao para corretores.\n\nImplementamos linguagem visual com foco em decisao rapida.",
                'results' => "Aumentou o volume de leads qualificados e a taxa de retorno para segunda visita.",
                'services' => ['Campanha de Lancamento', 'Material de Stand', 'Folder Comercial'],
                'tools' => ['Adobe InDesign', 'Adobe Photoshop'],
                'metrics' => [
                    ['label' => 'Leads qualificados', 'value' => '+44%', 'highlight' => true],
                    ['label' => 'Materiais produzidos', 'value' => '9 pecas', 'highlight' => false],
                    ['label' => 'Taxa de retorno', 'value' => '+19%', 'highlight' => true],
                ],
                'content' => "Pecas integradas com narrativa comercial do time de vendas, do primeiro contato ao fechamento.",
                'published_at' => now()->subDays(17),
                'seo_title' => 'Case: Materiais para Lancamento Imobiliario | Portfolio Uriah Criativa',
                'seo_description' => 'Case de stand imobiliario com impressos orientados a geracao de leads qualificados.',
                'focus_keyword' => 'material grafico para lancamento imobiliario',
            ],
            [
                'slug' => 'rotulos-artesanais-vale-mel',
                'title' => 'Rotulos Artesanais da Vale do Mel',
                'category_slug' => 'embalagens',
                'is_featured' => false,
                'client_name' => 'Vale do Mel',
                'industry' => 'Alimentos Artesanais',
                'location' => 'Florianopolis, SC',
                'project_year' => 2024,
                'project_url' => 'https://example.com/cases/vale-do-mel',
                'cover_image_url' => '/demo/banners/adesivamento-vinil.svg',
                'summary' => 'Desenvolvimento de sistema de rotulagem para linha de mel e derivados com foco em varejo especializado.',
                'challenge' => "A marca precisava destacar origem e variedade sem poluir visualmente os frascos.\n\nTambem era necessario facilitar leitura de informacoes obrigatorias.",
                'solution' => "Criamos familia de rotulos com codificacao por cor, icones de origem e hierarquia de leitura.\n\nAjustamos o arquivo para impressao em lotes variaveis.",
                'results' => "A nova linha melhorou reconhecimento no PDV e simplificou expansao de novos sabores.",
                'services' => ['Design de Rotulo', 'Padronizacao de Linha', 'Pre-impressao'],
                'tools' => ['Adobe Illustrator', 'Adobe Acrobat'],
                'metrics' => [
                    ['label' => 'SKUs cobertos', 'value' => '18 rotulos', 'highlight' => false],
                    ['label' => 'Tempo de aprovacao', 'value' => '-22%', 'highlight' => true],
                    ['label' => 'Recall visual', 'value' => '+31%', 'highlight' => true],
                ],
                'content' => "Estrutura visual pronta para crescimento de portfolio, mantendo unidade de marca em novos lancamentos.",
                'published_at' => now()->subDays(14),
                'seo_title' => 'Case: Sistema de Rotulos para Alimentos Artesanais | Portfolio Uriah Criativa',
                'seo_description' => 'Projeto de rotulos com codificacao visual por linha e foco em clareza no ponto de venda.',
                'focus_keyword' => 'design de rotulo para alimentos',
            ],
            [
                'slug' => 'ambientacao-lojas-bike-city',
                'title' => 'Ambientacao de Lojas Bike City',
                'category_slug' => 'comunicacao-visual',
                'is_featured' => false,
                'client_name' => 'Bike City',
                'industry' => 'Varejo Esportivo',
                'location' => 'Porto Alegre, RS',
                'project_year' => 2025,
                'project_url' => 'https://example.com/cases/bike-city',
                'cover_image_url' => '/demo/banners/comunicacao-visual-pdv.svg',
                'summary' => 'Projeto de comunicacao visual para padronizacao de experiencia em rede de lojas de bicicletas.',
                'challenge' => "As unidades tinham layouts diferentes e pouca consistencia de comunicacao.\n\nEra preciso criar unidade sem reformar toda a estrutura fisica.",
                'solution' => "Desenvolvemos sistema de adesivacao, sinalizacao setorial e pontos de destaque para ofertas.\n\nO projeto considerou implantacao faseada para manter operacao.",
                'results' => "As lojas passaram a comunicar melhor categorias e promocoes, aumentando percepcao de organizacao.",
                'services' => ['Ambientacao', 'Adesivacao', 'Sinalizacao de Varejo'],
                'tools' => ['Adobe Illustrator', 'CorelDRAW'],
                'metrics' => [
                    ['label' => 'Lojas padronizadas', 'value' => '11', 'highlight' => false],
                    ['label' => 'Tempo medio de busca', 'value' => '-24%', 'highlight' => true],
                    ['label' => 'Areas sinalizadas', 'value' => '57', 'highlight' => false],
                ],
                'content' => "A ambientacao foi planejada para ser escalavel, com biblioteca de pecas por setor de loja.",
                'published_at' => now()->subDays(11),
                'seo_title' => 'Case: Ambientacao para Rede de Lojas | Portfolio Uriah Criativa',
                'seo_description' => 'Case de comunicacao visual para varejo esportivo com foco em padronizacao de experiencia.',
                'focus_keyword' => 'ambientacao de loja',
            ],
            [
                'slug' => 'revista-institucional-clinica-vitta',
                'title' => 'Revista Institucional da Clinica Vitta',
                'category_slug' => 'editorial',
                'is_featured' => false,
                'client_name' => 'Clinica Vitta',
                'industry' => 'Saude',
                'location' => 'Londrina, PR',
                'project_year' => 2024,
                'project_url' => 'https://example.com/cases/clinica-vitta',
                'cover_image_url' => '/demo/banners/papelaria-premium.svg',
                'summary' => 'Producao editorial de revista institucional para relacionamento com pacientes e parceiros.',
                'challenge' => "A clinica precisava reforcar autoridade e humanizacao em um unico material.\n\nO conteudo tecnico exigia leitura simples e visual acolhedor.",
                'solution' => "Criamos projeto grafico editorial com sessoes recorrentes e linguagem acessivel.\n\nA edicao foi otimizada para impressao e distribuicao em consultorios.",
                'results' => "A revista fortaleceu a marca institucional e ampliou engajamento com conteudo de prevencao.",
                'services' => ['Design Editorial', 'Diagramacao', 'Gestao de Impressao'],
                'tools' => ['Adobe InDesign', 'Adobe Lightroom'],
                'metrics' => [
                    ['label' => 'Edicoes publicadas', 'value' => '4/ano', 'highlight' => false],
                    ['label' => 'Tempo medio de leitura', 'value' => '11 min', 'highlight' => false],
                    ['label' => 'Satisfacao dos leitores', 'value' => '94%', 'highlight' => true],
                ],
                'content' => "Material editorial com alta qualidade visual e narrativa orientada a educacao em saude.",
                'published_at' => now()->subDays(8),
                'seo_title' => 'Case: Revista Institucional na Area da Saude | Portfolio Uriah Criativa',
                'seo_description' => 'Projeto editorial para clinica com foco em autoridade, educacao e proximidade com pacientes.',
                'focus_keyword' => 'revista institucional para clinica',
            ],
        ];

        foreach ($projects as $row) {
            $project = PortfolioProject::query()->updateOrCreate(
                ['slug' => $row['slug']],
                [
                    'category_id' => $categories->get($row['category_slug'])?->id,
                    'author_id' => $admin?->id,
                    'title' => $row['title'],
                    'status' => 'published',
                    'is_featured' => (bool) $row['is_featured'],
                    'client_name' => $row['client_name'],
                    'industry' => $row['industry'],
                    'location' => $row['location'],
                    'project_year' => $row['project_year'],
                    'project_url' => $row['project_url'],
                    'cover_image_url' => $row['cover_image_url'],
                    'gallery_images' => [
                        [
                            'url' => $row['cover_image_url'],
                            'alt' => $row['title'],
                            'caption' => 'Visao geral do projeto',
                        ],
                    ],
                    'summary' => $row['summary'],
                    'challenge' => $row['challenge'],
                    'solution' => $row['solution'],
                    'results' => $row['results'],
                    'metrics' => $row['metrics'],
                    'services' => $row['services'],
                    'tools' => $row['tools'],
                    'content' => $row['content'],
                    'published_at' => $row['published_at'],
                    'views_count' => random_int(32, 310),
                    'seo_title' => $row['seo_title'],
                    'seo_description' => $row['seo_description'],
                    'focus_keyword' => $row['focus_keyword'],
                    'seo_canonical_url' => null,
                    'seo_og_title' => $row['seo_title'],
                    'seo_og_description' => $row['seo_description'],
                    'seo_og_image_url' => $row['cover_image_url'],
                    'seo_noindex' => false,
                ],
            );

            if ($project->trashed()) {
                $project->restore();
            }
        }
    }
}
